# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

value_count <- function(vec, target) {
    .Call(`_advporgrammingpart1_value_count`, vec, target)
}

gini_impurity_c <- function(left, right) {
    .Call(`_advporgrammingpart1_gini_impurity_c`, left, right)
}

best_split_c <- function(X, features, y) {
    .Call(`_advporgrammingpart1_best_split_c`, X, features, y)
}

fit_decision_stump_c <- function(X, features, y) {
    invisible(.Call(`_advporgrammingpart1_fit_decision_stump_c`, X, features, y))
}

value_count_v2 <- function(vec, target) {
    .Call(`_advporgrammingpart1_value_count_v2`, vec, target)
}

gini_impurity_c_v2 <- function(left, right) {
    .Call(`_advporgrammingpart1_gini_impurity_c_v2`, left, right)
}

best_split_c_v2 <- function(X, features, y) {
    .Call(`_advporgrammingpart1_best_split_c_v2`, X, features, y)
}

fit_decision_stump_c_v2 <- function(X, features, y) {
    invisible(.Call(`_advporgrammingpart1_fit_decision_stump_c_v2`, X, features, y))
}

rcpp_hello_world <- function() {
    .Call(`_advporgrammingpart1_rcpp_hello_world`)
}

